### PR TITLE
adds citation information (Issue-185)

### PR DESCRIPTION
**Pull request by SamFritz**
This PR addresses archivesunleashed.org [issue-185](https://github.com/archivesunleashed/archivesunleashed.org/issues/185): Include Citation Information.

Specifically, citation was added to the About the Project page, and creates a new subheading: Citing Archives Unleashed. Thought this would be the most appropriate place on the project website, but also happy for suggestions @ianmilligan1.

Work completed here is complementary to work outlined in [AUT issue-497](https://github.com/archivesunleashed/aut/issues/497). 

______________________________________________________________________________________________________________________________

Also, if a simpler structure is preferred (indent for citation, rather then added icon), we can use the following code in place of what is there for lines 19-28:

Citing Archives Unleashed 

How to cite the Archives Unleashed Toolkit or Cloud in your research:

* Nick Ruest, Jimmy Lin, Ian Milligan, and Samantha Fritz. 2020. The Archives Unleashed Project: Technology, Process, and Community to Improve Scholarly Access to Web Archives. In Proceedings of the ACM/IEEE Joint Conference on Digital Libraries in 2020 (JCDL '20). Association for Computing Machinery, New York, NY, USA, 157–166. DOI: https://doi.org/10.1145/3383583.3398513

Your citations help to further the recognition of using open-source tools for scientific inquiry, assists in growing the web archiving community, and acknowledges the efforts of contributors to this project.

### CODE REVIEW

**Review by ianmilligan1 — CHANGES_REQUESTED** [review]
I love this - esp. the citation icon and placement in the table. 

My only worry is that people might not see this on our `about` page - could we drop something similar in at the bottom of the Toolkit and Cloud pages, or would this make them too cluttered? (I am thinking out loud here)

**Comment by SamFritz** [comment]
Cool! 

We can certainly add to both Toolkit and Cloud pages as a just incase they don't immediately go to the about page. I think later down the road we should look at revisiting website structure to reduce repetitive info, but for right now I think this makes sense.

**Comment by SamFritz** [comment]
@ianmilligan1 added in citation bit on the bottom of Toolkit and Cloud pages. Looks good on Cloud page, 

However, when I did a view of Toolkit page using [http://localhost:1313/aut/](http://localhost:1313/aut/), the page doesn't render properly (e.g. video doesn't appear). But if I remember correctly we had this happen last time we updated .org pages?

**Comment by ianmilligan1** [comment]
I just took a look, @SamFritz, and seems to work on my end if I edit the [index.md](https://github.com/archivesunleashed/archivesunleashed.org/blob/issue-185/content/aut/index.md) page rather than the _index.md page. Let me push it up and see if it works on your end.

There may also be hugo versions at play - our theme is getting a bit creaky, unfortunately.

**Comment by SamFritz** [comment]
Thanks @ianmilligan1, sorry about implementing on wrong index page! 
Resolves better now, though video doesn't appear - but the code is there.

**Comment by ianmilligan1** [comment]
Perfect. I think that's probably a local hugo version issue, which we've run into with this theme before unfortunately. It's working on my end (0.57.0; I had to manually roll back to this one).

**Review by ianmilligan1 — APPROVED** [review]

**Pull request merged**
